'use client';

import {Karla} from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import {usePathname} from 'next/navigation'

const font = Karla({subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    const pathname = usePathname()

    return (
        <html lang="fr-FR" className={"dark"}>
        <body className={`${font.className} bg-background`}>
        <div vaul-drawer-wrapper={""}>
            <div className="flex dark bg-background shadow-md md:shadow-xl justify-between">
                <nav className="flex h-16 items-center px-4 gap-5">
                    <Link href={"/"}
                          className={`${pathname === '/' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                        InstantCiné
                    </Link>
                    <Link href={"/movie"}
                          className={`${pathname === '/movie' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                        Films
                    </Link>
                    <Link href={"/session"}
                          className={`${pathname === '/session' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                        Séances
                    </Link>
                </nav>
                <div className='flex items-center px-4 gap-2'>
                    <Link href={"/login"}
                          className={`${pathname === '/login' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                        Connexion
                    </Link>
                </div>
            </div>
            {children}
            {/*
        <footer className='flex flex-col gap-2 items-center dark bg-background text-white pt-5'>
          <div className='flex gap-5'>
            <div className='flex flex-col'>
              <h2 className='text-2xl'>Others side</h2>
              <Link href={"/movie"} className={`${pathname === '/movie' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Test1
              </Link>
              <Link href={"/session"} className={`${pathname === '/session' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Test2
              </Link>
            </div>
            <div className='flex flex-col'>
              <h2 className='text-2xl'>Plan du site</h2>
              <Link href={"/movie"} className={`${pathname === '/movie' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Films
              </Link>
              <Link href={"/session"} className={`${pathname === '/session' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Séances
              </Link>
            </div>
          </div>
          <p>  InstantCiné 2024 - Tout droits réservés</p>
        </footer>
        */}
        </div>
        </body>

        </html>
    )
}
