'use client';

import {Karla, Rubik} from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import {usePathname} from 'next/navigation'
import {Toaster} from "@/components/ui/sonner";

import Logo from "../../public/logo.svg"
import Image from "next/image";
import {SessionProvider} from "next-auth/react";
import {AuthProfileButton} from "@/components/auth-profile-button";

const font = Rubik({subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    const pathname = usePathname()

    return (
        <html lang="fr-FR" className={"dark"} suppressHydrationWarning>
        <body className={`${font.className} bg-background`}>
        <div vaul-drawer-wrapper={""}>
            <SessionProvider>

            <div className="flex dark bg-black bg-opacity-30 shadow-md md:shadow-xl justify-between">
                <nav className="flex py-2 items-center px-4 gap-8">
                    <Link href={"/"}
                          className={`${pathname === '/' && 'text-foreground/80'} transition-colors`}>
                        <Image src={Logo} width={100} height={100} alt={""} className={"w-[80px]"}/>
                    </Link>
                    <Link href={"/"}
                          className={`${pathname === '/' ? 'text-primary' : 'hover:text-foreground/80'} font-bold transition-colors  text-foreground text-lg`}>
                        Accueil
                    </Link>
                    <Link href={"/movies"}
                          className={`${pathname === '/movies' ? 'text-primary' : 'hover:text-foreground/80'} font-bold transition-colors  text-foreground text-lg`}>
                        Films
                    </Link>
                </nav>
                <div className='flex items-center px-4 gap-2'>
                    <AuthProfileButton />
                </div>
            </div>
                {children}
            {/*
        <footer className='flex flex-col gap-2 items-center dark bg-background text-white pt-5'>
          <div className='flex gap-5'>
            <div className='flex flex-col'>
              <h2 className='text-2xl'>Others side</h2>
              <Link href={"/movie"} className={`${pathname === '/movie' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Test1
              </Link>
              <Link href={"/session"} className={`${pathname === '/session' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Test2
              </Link>
            </div>
            <div className='flex flex-col'>
              <h2 className='text-2xl'>Plan du site</h2>
              <Link href={"/movie"} className={`${pathname === '/movie' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Films
              </Link>
              <Link href={"/session"} className={`${pathname === '/session' && 'text-foreground/80'} transition-colors hover:text-foreground/80 text-foreground/60`}>
                Séances
              </Link>
            </div>
          </div>
          <p>  InstantCiné 2024 - Tout droits réservés</p>
        </footer>
        */}
            </SessionProvider>

        </div>
    
        <Toaster position={"top-right"}/>
        </body>

        </html>
    )
}
